### ISSUE TITLE
Youtube video cannot be included in playlist

### ISSUE THREAD

**Issue by platisd** [DIT112-V21/group-06#42]
Hi,
Can you please remove the restrictions you've added to your video? I cannot include in the yearly playlist of videos. 😱

**Comment by Novenius** [comment]
Hi Dimitris,

Sorry for the late reply.

I have now removed the restrictions, so you should be able to add the video to your playlist.

Kind regards,
Richard a.k.a Papaloco

**Comment by platisd** [comment]
Thanks! :+1:
